**Tutorial 2: Numpy Stuff**

In [2]:
# display plots within (inline) the notebook
%matplotlib inline
import matplotlib.pylab as plt
import numpy as np

a = np.array([2,3,4,-1,3,-2]) # defines a 1d array
print("Shape of the array: a.shape =", a.shape)
print("Data type =", a.dtype)
print("Printing the array: a =")
print(a)

Shape of the array: a.shape = (6,)
Data type = int64
Printing the array: a =
[ 2  3  4 -1  3 -2]


In [4]:
b = np.array( [ [1.5, 2.3, 5.2], [4.2, 5.6, 4.4] ] )
print('Shape of the array, b.shape=', b.shape)
print('Data type, b.dtype', b.dtype)
print('Number of columns:', b.shape[-1]) # b.shape[1] is equivalent
print('Number of lines:', b.shape[-2]) # b.shape[0] is equivalent
print('Elements, b=')
print(b)

Shape of the array, b.shape= (2, 3)
Data type, b.dtype float64
Number of columns: 3
Number of lines: 2
Elements, b=
[[1.5 2.3 5.2]
 [4.2 5.6 4.4]]


In [16]:
# Creating arrays with initialized values

d = np.zeros(4)
print("0s array:")
print(d)
print(d.dtype)
print(d.shape)
print("\n")

d = np.ones((3,2), dtype="int16")
print("1s array:")
print(d)
print(d.dtype)
print(d.shape)
print("\n")

d = np.empty((2,3,2), "float")
print("Non-initialized array:")
print(d)
print(d.dtype)
print(d.shape)

0s array:
[0. 0. 0. 0.]
float64
(4,)


1s array:
[[1 1]
 [1 1]
 [1 1]]
int16
(3, 2)


Non-initialized array:
[[[1.14772635e-316 2.32210854e-322]
  [0.00000000e+000 0.00000000e+000]
  [6.95187041e-310 1.04082753e-047]]

 [[5.33359136e-091 3.92320724e+179]
  [1.00565549e-047 4.00964027e+174]
  [8.45276396e+252 1.46030983e-319]]]
float64
(2, 3, 2)


In [20]:
# Creating arrays with sequential values (linspace and arange)

print("np.arange(10) = ", np.arange(10)) # final value not included in the sequence with arange
print("np.arange(3,8) = ", np.arange(3,8))
print("np.arange(0,2,0.5) = ", np.arange(0,2,0.5))
print("np.linspace(0,2,5) = ", np.linspace(0,2,5))

np.arange(10) =  [0 1 2 3 4 5 6 7 8 9]
np.arange(3,8) =  [3 4 5 6 7]
np.arange(0,2,0.5) =  [0.  0.5 1.  1.5]
np.linspace(0,2,5) =  [0.  0.5 1.  1.5 2. ]


In [22]:
# 1D slicing

a = np.arange(20) # the indexes match the values of the array
print(a)
print("1D slicing a[1:15:2]")
print(a[1:15:2])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
1D slicing a[1:15:2]
[ 1  3  5  7  9 11 13]


In [23]:
# Slicing using negative indexes

a = np.arange(20)
print("a[1:-1:2]")
print(a[1:-1:2])
print("Observe that the last odd element (19) is not included")

a[1:-1:2]
[ 1  3  5  7  9 11 13 15 17]
Observe that the last odd element (19) is not included


In [24]:
# Inverting the array order

a = np.arange(20)
print("a = ")
print(a)
print("\n")
print("a inverted")
print(a[::-1])

a = 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


a inverted
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


**2D Array Slicing**

In [26]:
# Initializing an array and changing its shape

a = np.arange(20) # 1D array with 20 elements
print("a = ")
print(a)
print()

a = a.reshape(4,5) # reshape into a 4 row and 5 column 2D array
print("a.reshape(4,5) = ")
print(a)

a = 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

a.reshape(4,5) = 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [27]:
# Accessing lines and columns of an array

print("2nd line of a: ")
print(a[1,:])

print("First column of a: ")
print(a[:,0])

2nd line of a: 
[5 6 7 8 9]
First column of a: 
[ 0  5 10 15]


In [28]:
# Slicing specific rows and columns of an array

print("Getting every other line a[0::2,:] = ")
print(a[0::2,:])

print("Getting every other line and column starting at line 0 and column 1, a[0::2, 1::2] = ")
print(a[0::2, 1::2])

Getting every other line a[0::2,:] = 
[[ 0  1  2  3  4]
 [10 11 12 13 14]]
Getting every other line and column starting at line 0 and column 1, a[0::2, 1::2] = 
[[ 1  3]
 [11 13]]


In [31]:
# 2D slicing with inverted indexing

b = a[-1:-3:-1,:]
print('Getting the last 2 lines in reverse order, b = a[-1:-3:-1,:] = ')
print(b)

print("Getting the element in the last line and column, a[-1,-1] = ")
print(a[-1,-1])

c = a[::-1,:]
print("Inverting array lines: c = a[::-1,:] = ")
print(c)

Getting the last 2 lines in reverse order, b = a[-1:-3:-1,:] = 
[[15 16 17 18 19]
 [10 11 12 13 14]]
Getting the element in the last line and column, a[-1,-1] = 
19
Inverting array lines: c = a[::-1,:] = 
[[15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]


In [33]:
# Shallow copy example

a = np.arange(6)
b = a
print("a =")
print(a)
print("b =")
print(b)

b.shape = (2,3)
print("Shape of a =", a.shape)

b[0,0] = -1

print("id = ", id(a))
print("id = ", id(b))

print('np.may_share_memory(a,b): ', np.may_share_memory(a,b))


a =
[0 1 2 3 4 5]
b =
[0 1 2 3 4 5]
Shape of a = (2, 3)
a =
 [[-1  1  2]
 [ 3  4  5]]
[[-1  1  2]
 [ 3  4  5]]
[[-1  1  2]
 [ 3  4  5]]
id =  140710335073616
id =  140710335073616
np.may_share_memory(a,b):  True


In [34]:
def cc(a):
  return a

b = cc(a)
print("id of a = ", id(a))
print("id of b = ", id(b))
print("np.may_share_memory(a,b):", np.may_share_memory(a,b))

id of a =  140710335073616
id of b =  140710335073616
np.may_share_memory(a,b): True


There's a lot still that I'm not going to do, it's in his github tutorial files